### PR TITLE
Fix reviewer no cohorts

### LINKED ISSUE #135: Reviewers without apps to review
* Reviewers should see something if they login but have not been assigned to any cohorts (currently a blank page)

### PR DESCRIPTION
**Pull request by VictoriaVasys**
* Create alternate reviewer homepage if a reviewer has not been assigned to cohorts
* Update logic to pass correct cohort prop (add failsafes in case `Cohort.current` doesn't exist)

Closes #135

### CODE REVIEW

File: app/assets/javascripts/components/reviewer/reviewerDashboard.js.jsx [hunk 1]
```diff
@@ -4,17 +4,17 @@ class ReviewerDashboard extends React.Component {
     super(props)
 
     this.cohorts = JSON.parse(this.props.cohorts)
-    this.current_cohort = JSON.parse(this.props.current_cohort)
+    if(this.current_cohort){this.current_cohort = JSON.parse(this.props.current_cohort)}
     this.defineCurrentCohort()
-    this.current_cohort.title = this.current_cohort.title + ' (Current Cohort)'
+    if(this.current_cohort){this.current_cohort.title + ' (Current Cohort)'}
```
Comment (srt32) [inline app/assets/javascripts/components/reviewer/reviewerDashboard.js.jsx]: What does this line do? Should there be an assignment here somewhere?

File: app/assets/javascripts/components/reviewer/reviewerDashboard.js.jsx [hunk 2]
```diff
@@ -4,17 +4,17 @@ class ReviewerDashboard extends React.Component {
     super(props)
 
     this.cohorts = JSON.parse(this.props.cohorts)
-    this.current_cohort = JSON.parse(this.props.current_cohort)
+    if(this.current_cohort){this.current_cohort = JSON.parse(this.props.current_cohort)}
```
Comment (srt32) [inline app/assets/javascripts/components/reviewer/reviewerDashboard.js.jsx]: Maybe I'm misunderstanding but doesn't this line mean this line will never run since `this.current_cohort` is never set? Should this `if` be `if (this. props.current_cohort`?

File: app/assets/javascripts/components/reviewer/reviewerDashboard.js.jsx [hunk 3]
```diff
@@ -4,17 +4,17 @@ class ReviewerDashboard extends React.Component {
...
+    if(this.current_cohort){this.current_cohort.title + ' (Current Cohort)'}
     this.user = JSON.parse(this.props.user)
     this.authorization = 'Bearer ' + this.props.authorization
   }
   
   defineCurrentCohort() {
     return this.cohorts.map((cohort, i) => {
-      if (cohort.title == this.current_cohort.title) {
-        cohort.title = this.current_cohort.title + ' (Current Cohort)'
+      if (this.current_cohort && cohort.title === this.current_cohort.title) {
```
Comment (srt32) [inline app/assets/javascripts/components/reviewer/reviewerDashboard.js.jsx]: Out of curiosity, why are we doing equality comparison on `title` instead of `id`?

**Comment by srt32** [comment]
Left a couple questions but 🎉

**Comment by srt32** [comment]
@VictoriaVasys any reason not to merge here?

**Comment by srt32** [comment]
@VictoriaVasys good to merge here?

cc/ @icorson3

File: app/assets/javascripts/components/reviewer/reviewerDashboard.js.jsx (hunk 3 above)
Comment (VictoriaVasys) [reply app/assets/javascripts/components/reviewer/reviewerDashboard.js.jsx]: Great question; id is a much better choice.

File: app/assets/javascripts/components/reviewer/reviewerDashboard.js.jsx (hunk 2 above)
Comment (VictoriaVasys) [reply app/assets/javascripts/components/reviewer/reviewerDashboard.js.jsx]: Yes, wow- must've been really late when I made these changes. Thanks for the catches!

File: app/assets/javascripts/components/reviewer/reviewerDashboard.js.jsx (hunk 1 above)
Comment (VictoriaVasys) [reply app/assets/javascripts/components/reviewer/reviewerDashboard.js.jsx]: Yup, fixed.
